name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies for both frontend and backend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          if [ -f "yarn.lock" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      # Run tests for both frontend and backend
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: |
          if [ -f "yarn.lock" ]; then
            yarn test:coverage
          else
            npm run test:coverage
          fi

      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          if [ -f "yarn.lock" ]; then
            yarn test:coverage
          else
            npm run test:coverage
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

      - name: Create GitHub Issue on Quality Gate Failure
        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'failed'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = `
            # Code Quality Alert
            
            The code quality check has failed. Quality gate status: ${process.env.SONAR_QUALITY_GATE_STATUS}
            
            Please review the SonarCloud report for detailed analysis:
            [View detailed report](https://sonarcloud.io/dashboard?id=satyam4484)
            
            ## Action Required
            - Review and fix code quality issues
            - Ensure test coverage is above 70%
            - Address any code smells or security hotspots
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Code Quality Check Failed',
              body: issueBody,
              labels: ['code-quality', 'needs-attention']
            });