name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

      - name: Create GitHub Issue on Quality Gate Failure
        if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'failed'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const qualityMetrics = JSON.parse(process.env.SONAR_METRICS || '{}');
            const issueBody = `
            # Code Quality Alert
            
            The code quality check has failed. Here are the details:
            
            - Overall Code Quality: ${qualityMetrics.quality || 'N/A'}
            - Code Coverage: ${qualityMetrics.coverage || 'N/A'}%
            - Code Smells: ${qualityMetrics.codeSmells || 'N/A'}
            - Technical Debt: ${qualityMetrics.techDebt || 'N/A'}
            
            Please review and address these issues to maintain code quality standards.
            
            [View detailed report](https://sonarcloud.io/dashboard?id=${process.env.SONAR_PROJECT_KEY})
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Code Quality Check Failed',
              body: issueBody,
              labels: ['code-quality', 'needs-attention']
            });