name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Frontend Checks
      - name: Frontend - Install Dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Frontend - Type Check
        working-directory: ./frontend
        run: yarn type-check

      - name: Frontend - Run Tests
        working-directory: ./frontend
        run: yarn test:coverage

      # Backend Checks
      - name: Backend - Install Dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Backend - Run Tests
        working-directory: ./backend
        run: yarn test:coverage

      # Code Quality Check
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5